name: deep3d
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0
  - torchvision>=0.15
  - torchaudio>=2.0
  - pytorch-cuda=12.1
  - numpy
  - opencv
  - pillow
  - pip
  - pip:
    - tensorboard
